#!/usr/bin/env bash
#
# Aaron Zauner <azet@azet.org>
# CC0 1.0 - Public Domain Dedication
#
set -eu -o pipefail

stdin=$(</dev/stdin)

readonly sss="secretshare/target/release/secretshare"
readonly tmp_pwd="$(pwgen -s 64 -1)"
readonly majority="$(( ${#} / 2 + 1))"

(( ${#} < 3 )) && {
  printf "\nyou need at least three recipients for shamir secret sharing to be useful.\n\n"
  exit 1
}

[[ -f ${sss} ]] || {
  printf "\nsecretshare not built!\nget rust and 'cargo build --release'\n\n"
  exit 1
}

printf "%s recipients. majority reached at: %s.\n\n" ${#} ${majority}
readonly ciphertext=$(gpg --passphrase "${tmp_pwd}" -ac 2>/dev/null <<<${stdin})
secrets=$(${sss} -e${majority},${#} <<<${ciphertext})
for secret in ${secrets}; do
  msg="${secret} -> ${ciphertext}"
  gpg -ear "${1}" <<<${msg} | mail -s "SSS secret part for ${1}" ${1}
  shift
done
unset stdin msg
